## template: jinja
#cloud-config
# yamllint disable rule:document-start rule:line-length
groups:
  - docker
users:
  - default
  # the docker service account
  - name: docker-service
    groups: docker
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
write_files:
  - path: /etc/systemd/system/webapp.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Webapp in NGINX

      [Service]
      ExecStart=/usr/bin/docker run --rm --name webapp -p 80:80 -v /var/lib/webapp/html:/usr/share/nginx/html:ro -v /var/lib/webapp/conf.d:/etc/nginx/conf.d:ro nginx:alpine
      ExecStop=/usr/bin/docker stop webapp
      ExecStopPost=/usr/bin/docker rm webapp
  - path: /var/lib/webapp/html/index.html
    permissions: '0644'
    owner: root
    content: |
      <!DOCTYPE html>
      <html lang="en">
          <head>
              <title>Success</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link rel="stylesheet" href="//unpkg.com/purecss@2.0.6/build/pure-min.css" integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossorigin="anonymous">
              <link rel="stylesheet" href="//unpkg.com/purecss@2.0.6/build/grids-responsive-min.css" crossorigin="anonymous">
              <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" crossorigin="anonymous">
              <link rel="stylesheet" href="/styles.css">
          </head>
          <body>
              <div class="splash-container">
                  <div class="splash">
                      <h1 class="splash-head">F5 on {{ v1.cloud_name | upper }}</h1>
                      <p class="splash-subhead">
                          You know it makes sense!
                      </p>
                  </div>
              </div>
              <div class="content-wrapper">
                  <div class="ribbon l-box-lrg pure-g">
                      <div class="l-box-lrg is-center pure-u-1 pure-u-md-1-2 pure-u-lg-2-5">
                          <img src="/f5-logo-rgb.svg" alt="F5 logo" class="f5-logo">
                      </div>
                      <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-3-5">
                          <h2 class="content-head content-head-ribbon">Server details</h2>
                          <table class="pure-table">
                              <thead>
                                  <tr>
                                      <th>Field</th>
                                      <th>Value</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  <tr>
                                      <td>Hostname</td>
                                      <td>{{ v1.local_hostname }}</td>
                                  </tr>
                                  <tr>
                                      <td>Zone</td>
                                      <td>{{ v1.availability_zone }}</td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
                  <div class="footer l-box is-center">
                      Modified from <a href="https://purecss.io/">Pure CSS</a> Landing Page sample.
                  </div>
              </div>
          </body>
      </html>
  - path: /var/lib/webapp/html/styles.css
    permissions: '0644'
    owner: root
    encoding: gz+b64
    content: |
      ${styles_css}
  - path: /var/lib/webapp/html/f5-logo-rgb.svg
    permissions: '0644'
    owner: root
    encoding: gz+b64
    content: |
      ${f5_logo_rgb_svg}
  - path: /var/lib/webapp/conf.d/default.conf
    permissions: '0644'
    owner: root
    content: |
      server {
        listen 80 default_server;
        server_name _;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  # install webapp service
  - systemctl daemon-reload
  - systemctl start webapp.service
